insert into userprofile(address,email,name,phoneNo,userAccount_id) values('Gorakhpur','yogi@gmail.com','Yogi Aaditya nath',9873495921,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values('banaras','amulya@myName.com','Amulyann',9876543217,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values("B-25, sec-1, noida, 201301",'sdhsmm@gmail.com',"Sudhanshu Mishra",9953014536,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values("835,sec-3, vaishali,ghaziabad",'roshan@gmail.com','Roshan',9976359324,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values("B-25, sec-1, noida, 201301",'ravi@gmail.com',"Ravi Mishra",9964736248,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values("835,sec-4, vaishali,ghaziaba",'mmmmm@gmail.com',"sudhanshu m mishra",9875014794,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values('bareilly','alok@alok.com',"Alok Tripathi",8171912689,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values("vill: bhabhaya, post: gayaghat,belghat",'pratibha@prt.com',"km pratibha mishra",8673874628,NULL)
insert into userprofile(address,email,name,phoneNo,userAccount_id) values('B-25, sec-1, noida, 201301','s2dhsmm@gmail.com',"Sudhanshu2 Mishra2",9953014797,NULL)